(function(){
const B=window.OGE6_BANK,A=document.getElementById('app'),colors=['red','cyan','gold','purple','pink','green'];
const prizes=[{n:'Мишка со звездой',f:'prize-teddy.png'},{n:'Кролик с билетом',f:'prize-bunny.png'},{n:'Капибара-чемпион',f:'prize-capybara.png'},{n:'Утёнок с вертушкой',f:'prize-duck.png'},{n:'Лисёнок с подарком',f:'prize-fox.png'}];
const grandPrizes=[{n:'Королевский единорог',f:'grand-unicorn.png'},{n:'Изумрудный дракон-чемпион',f:'grand-dragon.png'},{n:'Коронованный аксолотль',f:'grand-axolotl.png'},{n:'Корги — обладатель кубка',f:'grand-corgi.png'},{n:'Звёздный кит',f:'grand-whale.png'}];
const empty={attempts:0,correct:0,streak:0,best:0,popped:{},cats:{}};
let s=load(),view='categories',cat=B.categories[0].name,page=0,catPage=0,q=null,state='idle';
function load(){try{let x=JSON.parse(localStorage.getItem('oge6-festival-stats')||'{}');return {...empty,...x,best:x.best??x.bestStreak??0,cats:x.cats??x.categories??{},popped:x.popped??{}}}catch{return {...empty}}}function save(){localStorage.setItem('oge6-festival-stats',JSON.stringify({...s,bestStreak:s.best,categories:s.cats}))}
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pct=(a,b)=>b?Math.round(a/b*100):0;
function header(){return `<header><button class="brand" data-go="categories"><span>◎</span><b>ОРФО·ТИР<small>задание 6 ОГЭ</small></b></button><nav><button data-go="categories">Орфограммы</button><button data-go="awards">Витрина наград</button><button data-go="stats">Статистика</button></nav></header>`}
function render(){A.innerHTML=header()+(view==='categories'?categories():view==='game'?game():view==='awards'?awards():stats())+(q?modal():'');bind()}
function categories(){let size=10,pages=Math.ceil(B.categories.length/size),start=catPage*size,items=B.categories.slice(start,start+size);return `<section class="location single-screen"><div class="location-title compact"><div><small>ЛЕТНИЙ ФЕСТИВАЛЬ ЗНАНИЙ · 30 СЕКТОРОВ</small><h1>Выберите витрину</h1><p>Завершите орфограмму — получите большую награду для общей витрины.</p></div><input id="search" placeholder="Найти орфограмму…"></div><div class="cat-grid compact-grid">${items.map((c,i)=>card(c,start+i)).join('')}</div><div class="cat-pages">${Array.from({length:pages},(_,i)=>`<button class="${i===catPage?'on':''}" data-catpage="${i}">${i+1}</button>`).join('')}</div></section>`}
function card(c,i){let done=B.questions.filter(x=>x.category===c.name&&s.popped[x.id]).length,cs=s.cats[c.name],complete=done===c.count,p=grandPrizes[i%grandPrizes.length];return `<button class="cat-card ${complete?'completed':''}" data-cat="${esc(c.name)}"><i class="awning"></i><i class="lights"></i><span class="num">${String(i+1).padStart(2,'0')}</span>${complete?`<span class="section-prize"><img src="assets/${p.f}"><i>ПРОЙДЕНО</i></span>`:`<span class="mini-ball ${colors[i%6]}">${i+1}</span>`}<span class="cat-text"><b>${esc(c.name)}</b><small>${complete?'Большой приз уже на витрине':esc(c.topics.slice(0,2).join(' · '))}</small></span><span class="play">${complete?'Повторить':'Играть ➜'}</span>${cs?`<strong>${pct(cs.correct,cs.attempts)}%</strong>`:''}<span class="progress"><i style="width:${pct(done,c.count)}%"></i><em>${done}/${c.count}</em></span></button>`}
function game(){let all=B.questions.filter(x=>x.category===cat),items=all.slice(page*12,page*12+12),done=all.filter(x=>s.popped[x.id]).length,pages=Math.ceil(all.length/12);return `<section class="game"><div class="toolbar"><button data-go="categories">← Все витрины</button><div><small>СЕКТОР ТИРА</small><h2>${esc(cat)}</h2></div><div class="live"><b>${done}<small>призов</small></b><b>${all.length-done}<small>осталось</small></b><b>${s.streak}<small>серия</small></b></div></div><div class="booth"><div class="sign"><b>НАВЕДИ ДРОТИК</b><small>выбери воздушный шарик</small></div><div class="balloons">${items.map(balloon).join('')}</div><div class="sector-progress">Прогресс сектора <b>${pct(done,all.length)}%</b><i><span style="width:${pct(done,all.length)}%"></span></i></div></div>${pages>1?`<div class="pages">${Array.from({length:pages},(_,i)=>`<button class="${i===page?'on':''}" data-page="${i}">${i+1}</button>`).join('')}</div>`:''}</section>`}
function balloon(x,i){let p=prizes[x.order%5];if(s.popped[x.id])return `<div class="won-prize" title="${esc(p.n)}"><img src="assets/${p.f}" alt="${esc(p.n)}"><span>ПРИЗ</span></div>`;return `<button class="balloon ${colors[(i+page*12)%6]}" data-q="${x.id}"><span>${page*12+i+1}</span></button>`}
function modal(){let p=prizes[q.order%5],sectionIndex=B.categories.findIndex(x=>x.name===cat),grand=grandPrizes[sectionIndex%grandPrizes.length];return `<div class="overlay"><div class="showcase ${state==='complete'?'grand-complete':''}"><button class="close" data-close>×</button>${state==='complete'?`<div class="grand-award"><div class="confetti">✦ · ✦ · ✦ · ✦ · ✦</div><small>ОРФОГРАММА ПРОЙДЕНА!</small><h2>${esc(cat)}</h2><div class="grand-prize"><img src="assets/${grand.f}"><span>БОЛЬШАЯ НАГРАДА</span></div><h3>${esc(grand.n)}</h3><p>Все шарики этого сектора сбиты. Награда уже размещена на витрине пройденных разделов.</p><div><button data-go="awards">Открыть витрину</button><button data-close>Остаться в тире</button></div></div>`:`<div class="marquee"><i>🎯</i><small>ЗАДАНИЕ ИЗ ШАРИКА</small><b>${esc(q.category)}</b><span>${esc(q.topic)}</span></div><div class="quest"><div class="quest-ball"><b>${(q.order%99)+1}</b></div><div class="copy"><small>ВЕРНО ЛИ ОБЪЯСНЕНИЕ?</small><h3>${esc(q.word)}</h3><p>${esc(q.statement)}</p></div>${state==='idle'?`<div class="answers"><button class="yes" data-answer="true"><i>✓</i><b>Верно</b><small>объяснение точное</small></button><button class="no" data-answer="false"><i>×</i><b>Неверно</b><small>в объяснении ошибка</small></button></div>`:state==='right'?`<div class="result right"><img src="assets/${p.f}"><div><small>ТОЧНО В ЦЕЛЬ!</small><h4>${esc(p.n)}</h4><p>Шарик лопнул, а приз занял его место на стенде.</p><button data-close>Забрать и продолжить ➜</button></div></div>`:`<div class="result wrong"><div class="retry">↺</div><div><small>ПОКА МИМО</small><h4>Шарик остался</h4><p>Правильный ответ: <b>${q.correct?'объяснение верное':'объяснение неверное'}</b>.</p><button data-close>Вернуться в тир</button></div></div>`}</div><footer>Исходное задание № ${q.sourceTask}, пункт ${q.option}</footer>`}</div></div>`}
function completedCategories(){return B.categories.map((c,i)=>({c,i,done:B.questions.filter(x=>x.category===c.name&&s.popped[x.id]).length})).filter(x=>x.done===x.c.count)}
function awards(){let won=completedCategories();return `<section class="awards single-screen"><div class="awards-head"><div><small>КОЛЛЕКЦИЯ ДОСТИЖЕНИЙ</small><h1>Витрина наград</h1><p>${won.length?`Пройдено разделов: ${won.length} из ${B.categories.length}`:'Завершите первую орфограмму — и здесь появится большая награда.'}</p></div><button data-go="categories">Продолжить игру ➜</button></div><div class="award-cabinet">${won.length?won.map(({c,i})=>{let p=grandPrizes[i%grandPrizes.length];return `<article><div><img src="assets/${p.f}"><span>✦ БОЛЬШОЙ ПРИЗ ✦</span></div><h3>${esc(c.name)}</h3><p>${esc(p.n)}</p></article>`}).join(''):`<div class="empty-cabinet"><span>🏆</span><h2>Витрина пока пуста</h2><p>Большой приз выдаётся, когда сбиты все шарики одной орфограммы.</p></div>`}</div></section>`}
function stats(){let acc=pct(s.correct,s.attempts),entries=Object.entries(s.cats);return `<section class="stats"><div class="stats-head"><div><small>ЛИЧНАЯ КАРТОЧКА ИГРОКА</small><h1>Статистика</h1></div><button data-reset>Сбросить прогресс</button></div><div class="stat-hero"><div class="ring" style="--p:${acc*3.6}deg"><b>${acc}%</b><small>точность</small></div><div class="totals"><b>${s.attempts}<small>ответов</small></b><b>${s.correct}<small>верных</small></b><b>${Object.keys(s.popped).length}<small>призов</small></b><b>${s.best}<small>лучшая серия</small></b></div><div class="shelf">${prizes.map(p=>`<img src="assets/${p.f}">`).join('')}</div></div><div class="stat-list"><h2>По орфограммам</h2>${entries.length?entries.map(([n,v])=>`<div><span>${esc(n)}</span><i><b style="width:${pct(v.correct,v.attempts)}%"></b></i><strong>${pct(v.correct,v.attempts)}%</strong></div>`).join(''):'<p>Пока нет ответов.</p>'}</div></section>`}
function answer(v){let ok=v===q.correct,c=s.cats[cat]||{attempts:0,correct:0},all=B.questions.filter(x=>x.category===cat),wasComplete=all.every(x=>s.popped[x.id]);s={...s,attempts:s.attempts+1,correct:s.correct+(ok?1:0),streak:ok?s.streak+1:0,best:Math.max(s.best,ok?s.streak+1:0),popped:ok?{...s.popped,[q.id]:1}:s.popped,cats:{...s.cats,[cat]:{attempts:c.attempts+1,correct:c.correct+(ok?1:0)}}};let nowComplete=all.every(x=>s.popped[x.id]);state=ok&&!wasComplete&&nowComplete?'complete':ok?'right':'wrong';save();render()}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{view=b.dataset.go;q=null;render()});document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;page=0;view='game';render()});document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=+b.dataset.page;render()});document.querySelectorAll('[data-catpage]').forEach(b=>b.onclick=()=>{catPage=+b.dataset.catpage;render()});document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{q=B.questions.find(x=>x.id===b.dataset.q);state='idle';render()});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{q=null;render()});document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer==='true'));let z=document.getElementById('search');if(z)z.oninput=()=>{let term=z.value.trim().toLowerCase();if(!term){render();return}let list=B.categories.map((c,i)=>({c,i})).filter(x=>x.c.name.toLowerCase().includes(term)||x.c.topics.join(' ').toLowerCase().includes(term)),grid=document.querySelector('.cat-grid'),pager=document.querySelector('.cat-pages');grid.innerHTML=list.map(x=>card(x.c,x.i)).join('');pager.hidden=true;grid.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;page=0;view='game';render()})};let r=document.querySelector('[data-reset]');if(r)r.onclick=()=>{if(confirm('Сбросить статистику?')){s={...empty,popped:{},cats:{}};save();render()}}}
render();
})();
